version: '3.7'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.1.0
    ports:
      - 5000:8080
    networks:
      - tyk
    volumes:
      - ./tyk-gateway/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk-gateway/apps:/opt/tyk-gateway/apps
      - ./tyk-gateway/middleware:/opt/tyk-gateway/middleware
      - ./tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./tyk-gateway/policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis

  tyk-redis:
    image: redis:6.2.7-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
  tyk: